# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: pub-quiz-env

steps:
  - task: UseNode@1
    inputs:
      version: '10.x'

  - script: yarn
    displayName: 'Install dependencies'

  - script: DATABASE=$(DATABASE) FB_API_KEY=$(FB_API_KEY) FB_APP_ID=$(FB_APP_ID) FB_AUTH_DOMAIN=$(FB_AUTH_DOMAIN) FB_DATABASE_URL=$(FB_DATABASE_URL) FB_MEASUREMENT_ID=$(FB_MEASUREMENT_ID) FB_MESSAGING_SENDER_ID=$(FB_MESSAGING_SENDER_ID) FB_PROJECT_ID=$(FB_PROJECT_ID) FB_STORAGE_BUCKET=$(FB_STORAGE_BUCKET) GOOGLE_APPLICATION_CREDENTIALS=$(GOOGLE_APPLICATION_CREDENTIALS) yarn createDotEnv
    displayName: 'Build dotenv file'

  - script: yarn build
    displayName: 'Run build'
