# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@1
    inputs:
      version: '13.x'

  - script: yarn
    displayName: 'Install dependencies'

  - script: yarn build
    displayName: 'Run build'

  - script: yarn build:package
    displayName: 'Run package'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: CopyFiles@2
    inputs:
      SourceFolder: './src/server'
      Contents: 'data.json'
      TargetFolder: './dist/server'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - script: cd ./dist/server && yarn && cd ..
    displayName: 'Install prod dependencies'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: './dist'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/pub-quiz-$(Build.BuildId).zip'
      replaceExistingArchive: true
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'pub-quiz-$(Build.BuildId).tar.gz'
      publishLocation: 'Container'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))