# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@1
    inputs:
      version: '13.x'

  - script: yarn
    displayName: 'Install dependencies'

  - script: yarn build
    displayName: 'Run build'

  - script: yarn build:package
    displayName: 'Run package'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: CopyFiles@2
    inputs:
      SourceFolder: './src/server'
      Contents: 'data.json'
      TargetFolder: './dist/server'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - script: cd ./dist/server && yarn && cd ..
    displayName: 'Install prod dependencies'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: CopyFiles@2
    inputs:
      Contents: 'dist/**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - task: PublishBuildArtifacts@1
    inputs: 
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: 'pub-quiz'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))